apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: victoria-metrics-operator
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.43.1
    releaseName: victoria-metrics-operator
    namespace: lab101-victoria-metrics-operator
    valuesFile: values.yaml
