apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 9.0.3
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP
  config:
    elasticsearch.requestTimeout: 60000  # 60 seconds
    elasticsearch.shardTimeout: 60000    # 60 seconds
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: kibana.vinlab.org
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: kibana.vinlab.org
    http:
      paths:
        - backend:
            service:
              name: kibana-kb-http
              port:
                number: 5601
          path: /
          pathType: Prefix
  tls:
    - hosts:
        - kibana.vinlab.org
      secretName: defaultcert
