---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: docker-containers
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  tail:
    path: /var/log/containers/*.log
    parser: docker

