# https://github.com/fluent/fluent-operator/tree/master/manifests/logging-stack
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab101-fluent
resources:
  - fluent-bit-cluster.yaml
  - fluent-bit--systemd.yaml
  - fluent-bit-output--es.yaml

helmCharts:
  - name: vault-static-secret
    version: 0.1.2
    repo: https://vintechlab.github.io/vinhelm
    releaseName: vault-static-secret
    valuesInline:
      auth:
        mount: kubernetes
      secrets:
      - path: vinlab/logging/esticsearch/users/fluent-bit
        name: elasticsearch-fluent-bit-user
        destination: elasticsearch-fluent-bit-user

