apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
spec:
  selectAllByDefault: true
  remoteWrite:
    - url: "http://vminsert-vmcluster.lab101-metrics.svc:8480/insert/0/prometheus/api/v1/write"
  remoteWriteSettings:
    label:
      k8s_cluster: vinlab
      cluster: vinlab
