apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: vinlab
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "192.168.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: true
