apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-operator
resources:
  - namespace.yaml
  - argocd-operator-crd-v0.12.2.yaml
patches:
  - path: patches.yaml
    target:
      kind: Deployment
      name: argocd-operator-controller-manager
      namespace: argocd-operator
      version: v1

images:
  - name: quay.io/argoprojlabs/argocd-operator
    newTag: v0.12.2-patch-003
    newName: docker.io/icymatter/argocd-operator
