namespace: lab101-redis-operator
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/spotahome/redis-operator/v1.3.0-rc1/manifests/databases.spotahome.com_redisfailovers.yaml
helmCharts:
  - name: redis-operator
    repo: https://spotahome.github.io/redis-operator
    version: 3.3.0
    releaseName: redis-operator
    valuesFile: values.yaml
