apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: postgres-cluster
spec:
  dockerImage: ghcr.io/zalando/spilo-17:4.0-p2
  teamId: vinlab
  numberOfInstances: 2
  postgresql:
    version: "17"
    parameters:
      shared_buffers: 128MB
      max_connections: "10"
      log_statement: all
  volume:
    size: 10Gi
  additionalVolumes:
    - name: empty
      mountPath: /opt/empty
      targetContainers:
        - all
      volumeSource:
        emptyDir: {}
  enableShmVolume: true
  patroni:
    failsafe_mode: false
    initdb:
      encoding: UTF8
      locale: en_US.UTF-8
      data-checksums: "true"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  users:
    vinlab:
    - superuser
    - createdb
  databases:
    vinlab: vinlab
  preparedDatabases:
    vinlab:
      defaultUsers: true
