namespace: lab101-mysql-operator
resources:
  - namespace.yaml
  - crd.yaml
helmCharts:
  - name: mysql-operator
    repo: https://mysql.github.io/mysql-operator
    version: 2.2.4
    releaseName: mysql-operator
    valuesFile: values.yaml
