---
global:
  resolve_timeout: 5s
route:
  receiver: slack
  group_interval: 5s
  routes:
    - receiver: slack
      matchers:
        - severity="critical"
        - channel="slack"
      continue: false
receivers:
  - name: slack
    slack_configs:
      - channel: "#alerts"
        api_url_file: /etc/vm/secrets/slack-webhook/url 
        send_resolved: true
        username: Alertmanager
        icon_emoji: ":ghost:"
