apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: phamtanvinh.me@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: phamtanvinh.me@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
