apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml

helmCharts:
  - name: cert-manager
    version: v1.16.2
    repo: https://charts.jetstack.io
    namespace: cert-manager
    releaseName: cert-manager
    valuesFile: values.yaml

  - name: vault-static-secret
    version: 0.1.2
    repo: https://vintechlab.github.io/vinhelm
    releaseName: vault-static-secret
    valuesInline:
      auth:
        mount: kubernetes
        role: vault-role
      secrets:
        - name: cloudflare-api-token-secret
          path: vinlab/cloudflare/api-tokens/edit-zone-dns
          destination: cloudflare-api-token-secret


