apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-secrets-operator
resources:
  - namespace.yaml
  - roles.yaml
  - https://raw.githubusercontent.com/hashicorp/vault-secrets-operator/main/config/crd/bases/secrets.hashicorp.com_vaultconnections.yaml
helmCharts:
  - name: vault-secrets-operator
    version: 0.9.1
    repo: https://helm.releases.hashicorp.com
    releaseName: vault-secrets-operator
    valuesFile: values.yaml
