defaultVaultConnection:
  enabled: true
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: false

controller:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                  - "true"
