apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-operator
resources:
  - namespace.yaml
helmCharts:
  - name: tailscale-operator
    version: 1.78.3
    repo: https://pkgs.tailscale.com/helmcharts
    namespace: tailscale-operator
    releaseName: tailscale-operator
    valuesFile: values.yaml

  - name: vault-static-secret
    version: 0.1.2
    repo: https://raw.githubusercontent.com/phamtanvinh/helmcharts/main
    releaseName: vault-static-secret
    valuesFile: values-vault-static-secret.yaml
