apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    security:
      admin_user: root
      admin_password: root
    log:
      mode: "console"
    paths:
      data: /var/lib/grafana
    plugins:
      allow_loading_unsigned_plugins: "victoriametrics-datasource"
    server:
      root_url: https://grafana.vinlab.org
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/hostname: grafana.vinlab.org
        kubernetes.io/tls-acme: "true"
    spec:
      ingressClassName: nginx
      tls:
        - hosts:
            - grafana.vinlab.org
          secretName: defaultcert
      rules:
        - host: grafana.vinlab.org
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix

  deployment:
    spec:
      replicas: 1
      template:
        spec:
          initContainers:
            - name: "load-vm-ds-plugin"
              image: "curlimages/curl:7.85.0"
              command: ["/bin/sh"]
              workingDir: "/var/lib/grafana"
              securityContext:
                runAsUser: 0
                runAsNonRoot: false
                runAsGroup: 0
              args:
                - "-c"
                - |
                  set -ex
                  mkdir -pv /var/lib/grafana/plugins
                  curl -L https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.9.0/victoriametrics-datasource-v0.9.0.tar.gz -o /var/lib/grafana/plugins/vm-plugin.tar.gz
                  tar -xf /var/lib/grafana/plugins/vm-plugin.tar.gz -C /var/lib/grafana/plugins/
                  rm /var/lib/grafana/plugins/vm-plugin.tar.gz
                  chown -Rc 472:472 /var/lib/grafana/

              volumeMounts:
                - name: grafana-data
                  mountPath: /var/lib/grafana
          containers:
            - name: grafana
              volumeMounts:
                - name: grafana-data
                  mountPath: /var/lib/grafana
              securityContext:
                runAsUser: 472
                runAsNonRoot: true
                runAsGroup: 472
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  persistentVolumeClaim:
    metadata:
      labels:
        dashboards: grafana
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: openebs-hostpath
