---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover-cluster
spec:
  auth:
    secretPath: redis-auth
  sentinel:
    replicas: 3
    # extraVolumes:
    # - name: redis-auth
    #   secret:
    #     secretName: redis-auth
    #     optional: false
    # extraVolumeMounts:
    # - name: redis-auth
    #   mountPath: "/etc/redis-auth"
    #   readOnly: true
  redis:
    replicas: 3
    # extraVolumes:
    # - name: redis-auth
    #   secret:
    #     secretName: redis-auth
    #     optional: false
    # extraVolumeMounts:
    # - name: redis-auth
    #   mountPath: "/etc/redis-auth"
    #   readOnly: true
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-persistent-data
        spec:
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
