provider:
  name: cloudflare
env:
  - name: CF_API_EMAIL
    value: phamtanvinh.me@gmail.com
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: token
serviceMonitor:
  enabled: false
txtOwnerId: vinlab
domainFilters:
  - vinlab.org
policy: sync
