---
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: node-role.kubernetes.io/worker
      operator: Equal
      value: "true"
      effect: NoSchedule
- op: add
  path: /spec/template/spec/nodeSelector
  value:
    node-role.kubernetes.io/worker: "true"

- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: "ENABLE_CONVERSION_WEBHOOK"
    value: "false"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: "ARGOCD_CLUSTER_CONFIG_NAMESPACES"
    value: "*"

# - op: add
#   path: /spec/template/spec/containers/0/env/-
#   value:
#     name: "CLUSTER_DNS_DOMAIN"
#     value: "mango.dwhlocal"

# Remove the manager container's "cert" volumeMount, since OLM will create and mount a set of certs.
# Update the indices in this path if adding or removing containers/volumeMounts in the manager's Deployment.
- op: remove
  path: /spec/template/spec/containers/0/volumeMounts/0
# Remove the "cert" volume, since OLM will create and mount a set of certs.
# Update the indices in this path if adding or removing volumes in the manager's Deployment.
- op: remove
  path: /spec/template/spec/volumes/0
