apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab101-fluent
resources:
  - fluent-bit-crds.yaml
  - fluentd-crds.yaml
helmCharts:
- name: fluent-operator
  version: 3.4.0
  repo: https://fluent.github.io/helm-charts
  releaseName: fluent-operator
  valuesFile: values.yaml
