apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - namespace.yaml
helmCharts:
  - name: ingress-nginx
    version: 4.11.3
    repo: https://kubernetes.github.io/ingress-nginx
    namespace: ingress-nginx
    releaseName: ingress-nginx
    valuesFile: values.yaml
