apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: vmalertmanager
spec:
  replicaCount: 1
  selectAllByDefault: true
  configSelector:
    matchLabels:
      app: alertmanager
  image:
    repository: prom/alertmanager
    tag: v0.27.0
    pullPolicy: IfNotPresent
  serviceSpec:
    spec:
      type: ClusterIP
      ports:
        - name: http
          port: 9093
          targetPort: 9093
          protocol: TCP
  configSecret: vmalertmanager-config
  secrets:
    - slack-webhook
