apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab101-metrics
resources:
  - alertmanager.yaml
  - alert.yaml
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: vmalertmanager-config
    files:
      - alertmanager.yaml=kconfig/alertmanager.yaml

helmCharts:
  - name: vault-static-secret
    version: 0.1.2
    repo: https://raw.githubusercontent.com/phamtanvinh/helmcharts/main
    releaseName: vault-static-secret
    valuesInline:
      auth:
        mount: kubernetes
      secrets:
        - name: slack-webhook
          path: vinlab/slack/webhook
          destination: slack-webhook

