---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: This project will contains all applications in kiwi folder
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  generators:
    - git:
        repoURL: git@gitlab.com:vin-fusion-reactor/vinlab.git
        revision: HEAD
        directories:
          - path: k8s/lab101*/*

  goTemplate: true
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: argocd
      source:
        repoURL: git@gitlab.com:vin-fusion-reactor/vinlab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename }}'
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - ServerSideApply=true
          - FailOnSharedResource=true
      revisionHistoryLimit: 3
