auth:
  mount: kubernetes
  role: infra

secrets:
  - name: repo-vinlab
    path: vinlab/argocd/repositories/github/vinlab
    destination: repo-vinlab
    labels:
      argocd.argoproj.io/secret-type: repo-creds

  # - name: argocd-artifact-registry-secret
  #   path: vinlab/gcp/sandbox/serviceaccounts/sandbox-artifact-registry
  #   destination: argocd-artifact-registry-secret

  # - name: cluster-kind-vinlab
  #   path: vinlab/argocd/servers/kind-vinlab
  #   destination: cluster-kind-vinlab
  #   labels:
  #     argocd.argoproj.io/secret-type: cluster
