apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - namespace.yaml
helmCharts:
  - name: external-dns
    version: 1.15.0
    repo: https://kubernetes-sigs.github.io/external-dns
    releaseName: external-dns
    valuesFile: values.yaml

  - name: vault-static-secret
    version: 0.1.2
    repo: https://vintechlab.github.io/vinhelm
    releaseName: vault-static-secret
    valuesInline:
      auth:
        mount: kubernetes

      secrets:
        - name: cloudflare-api-token-secret
          path: vinlab/cloudflare/api-tokens/edit-zone-dns
          destination: cloudflare-api-token-secret
