apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab101-airflow
resources:
  - namespace.yaml
  - storages.yaml
helmCharts:
  - name: airflow
    version: 1.15.0
    repo: https://airflow.apache.org
    namespace: lab101-airflow
    releaseName: lab101-airflow
    valuesFile: values.yaml

  - name: vault-static-secret
    version: 0.1.2
    repo: https://vintechlab.github.io/vinhelm
    releaseName: vault-static-secret
    valuesInline:
      auth:
        mount: kubernetes
        role: dataplatform

      secrets:
        - name: airflow-common-secrets
          path: vinlab/dataplatform/airflow/airflow-common-secrets
          destination: airflow-common-secrets

