apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.8.88
    path: /shared_data/airflow/dags
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-dags
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-plugins
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.8.88
    path: /shared_data/airflow/plugins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-plugins
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.8.88
    path: /shared_data/airflow/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-logs
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
