apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - namespace.yaml
helmCharts:
  - name: vault
    version: 0.29.1
    repo: https://helm.releases.hashicorp.com
    releaseName: vault
    valuesFile: values.yaml
